export interface DetailPekerjaanResponse {
  id: string;
  id_asset: string | null;
  id_tipe: string;
  id_kategori: string | null;
  id_kategori_group: string | null;
  berkas_foto: string | null;
  id_parameter: string;
  nama_parameter: string;
  kode: string;
  nama_asset: string;
  no_spk: string;
  tanggal_penilaian: string;
  pemohon: string;
  id_petugas_1: string;
  petugas_1: string;
  is_penyedia: string;
  qr_code: string;
  id_petugas_2: string | null;
  petugas_2: string | null;
  id_petugas_3: string | null;
  petugas_3: string | null;
  status: string;
  keterangan: string;
  latitude: number;
  longitude: number;
  polygon: string | null;
  icon: string | null;
  tanggal_perolehan: string | null;
  tanggal_digunakan: string | null;
  tanggal_penilaian_terakhir: string | null;
  skor_penilaian_terakhir: string | null;
  masa_pakai: string | null;
  keterangan_asset: string | null;
  lokasi: string;
  foto_1: string | null;
  foto_2: string | null;
  foto_3: string | null;
  kode_bagian: string | null;
  kode_golongan_susut: string | null;
  kode_cabang: string | null;
  kode_gedung: string | null;
  kode_ruangan: string | null;
  kode_tipe: string;
  kode_kategori: string | null;
  bagian: string;
  golongan_susut: string | null;
  persentase_susut: string | null;
  cabang: string | null;
  gedung: string;
  ruangan: string;
  tipe: string;
  kategori: string | null;
  is_aset_terdaftar: number;
}
