/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as authenticatedImport } from './routes/__authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as authenticatedUbahPasswordImport } from './routes/__authenticated/ubah-password'
import { Route as authenticatedSelesaiImport } from './routes/__authenticated/selesai'
import { Route as authenticatedQrscanImport } from './routes/__authenticated/qrscan'
import { Route as authenticatedProfileImport } from './routes/__authenticated/profile'
import { Route as authenticatedPekerjaanImport } from './routes/__authenticated/pekerjaan'
import { Route as authenticatedDashboardImport } from './routes/__authenticated/dashboard'
import { Route as authenticatedAkunImport } from './routes/__authenticated/akun'
import { Route as authenticatedPenilaianIdpenilaianImport } from './routes/__authenticated/penilaian/$id_penilaian'
import { Route as authenticatedDetailIdImport } from './routes/__authenticated/detail/$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const authenticatedRoute = authenticatedImport.update({
  id: '/__authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authenticatedUbahPasswordRoute = authenticatedUbahPasswordImport.update({
  id: '/ubah-password',
  path: '/ubah-password',
  getParentRoute: () => authenticatedRoute,
} as any)

const authenticatedSelesaiRoute = authenticatedSelesaiImport.update({
  id: '/selesai',
  path: '/selesai',
  getParentRoute: () => authenticatedRoute,
} as any)

const authenticatedQrscanRoute = authenticatedQrscanImport.update({
  id: '/qrscan',
  path: '/qrscan',
  getParentRoute: () => authenticatedRoute,
} as any)

const authenticatedProfileRoute = authenticatedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authenticatedRoute,
} as any)

const authenticatedPekerjaanRoute = authenticatedPekerjaanImport.update({
  id: '/pekerjaan',
  path: '/pekerjaan',
  getParentRoute: () => authenticatedRoute,
} as any)

const authenticatedDashboardRoute = authenticatedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authenticatedRoute,
} as any)

const authenticatedAkunRoute = authenticatedAkunImport.update({
  id: '/akun',
  path: '/akun',
  getParentRoute: () => authenticatedRoute,
} as any)

const authenticatedPenilaianIdpenilaianRoute =
  authenticatedPenilaianIdpenilaianImport.update({
    id: '/penilaian/$id_penilaian',
    path: '/penilaian/$id_penilaian',
    getParentRoute: () => authenticatedRoute,
  } as any)

const authenticatedDetailIdRoute = authenticatedDetailIdImport.update({
  id: '/detail/$id',
  path: '/detail/$id',
  getParentRoute: () => authenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__authenticated': {
      id: '/__authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/__authenticated/akun': {
      id: '/__authenticated/akun'
      path: '/akun'
      fullPath: '/akun'
      preLoaderRoute: typeof authenticatedAkunImport
      parentRoute: typeof authenticatedImport
    }
    '/__authenticated/dashboard': {
      id: '/__authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardImport
      parentRoute: typeof authenticatedImport
    }
    '/__authenticated/pekerjaan': {
      id: '/__authenticated/pekerjaan'
      path: '/pekerjaan'
      fullPath: '/pekerjaan'
      preLoaderRoute: typeof authenticatedPekerjaanImport
      parentRoute: typeof authenticatedImport
    }
    '/__authenticated/profile': {
      id: '/__authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof authenticatedProfileImport
      parentRoute: typeof authenticatedImport
    }
    '/__authenticated/qrscan': {
      id: '/__authenticated/qrscan'
      path: '/qrscan'
      fullPath: '/qrscan'
      preLoaderRoute: typeof authenticatedQrscanImport
      parentRoute: typeof authenticatedImport
    }
    '/__authenticated/selesai': {
      id: '/__authenticated/selesai'
      path: '/selesai'
      fullPath: '/selesai'
      preLoaderRoute: typeof authenticatedSelesaiImport
      parentRoute: typeof authenticatedImport
    }
    '/__authenticated/ubah-password': {
      id: '/__authenticated/ubah-password'
      path: '/ubah-password'
      fullPath: '/ubah-password'
      preLoaderRoute: typeof authenticatedUbahPasswordImport
      parentRoute: typeof authenticatedImport
    }
    '/__authenticated/detail/$id': {
      id: '/__authenticated/detail/$id'
      path: '/detail/$id'
      fullPath: '/detail/$id'
      preLoaderRoute: typeof authenticatedDetailIdImport
      parentRoute: typeof authenticatedImport
    }
    '/__authenticated/penilaian/$id_penilaian': {
      id: '/__authenticated/penilaian/$id_penilaian'
      path: '/penilaian/$id_penilaian'
      fullPath: '/penilaian/$id_penilaian'
      preLoaderRoute: typeof authenticatedPenilaianIdpenilaianImport
      parentRoute: typeof authenticatedImport
    }
  }
}

// Create and export the route tree

interface authenticatedRouteChildren {
  authenticatedAkunRoute: typeof authenticatedAkunRoute
  authenticatedDashboardRoute: typeof authenticatedDashboardRoute
  authenticatedPekerjaanRoute: typeof authenticatedPekerjaanRoute
  authenticatedProfileRoute: typeof authenticatedProfileRoute
  authenticatedQrscanRoute: typeof authenticatedQrscanRoute
  authenticatedSelesaiRoute: typeof authenticatedSelesaiRoute
  authenticatedUbahPasswordRoute: typeof authenticatedUbahPasswordRoute
  authenticatedDetailIdRoute: typeof authenticatedDetailIdRoute
  authenticatedPenilaianIdpenilaianRoute: typeof authenticatedPenilaianIdpenilaianRoute
}

const authenticatedRouteChildren: authenticatedRouteChildren = {
  authenticatedAkunRoute: authenticatedAkunRoute,
  authenticatedDashboardRoute: authenticatedDashboardRoute,
  authenticatedPekerjaanRoute: authenticatedPekerjaanRoute,
  authenticatedProfileRoute: authenticatedProfileRoute,
  authenticatedQrscanRoute: authenticatedQrscanRoute,
  authenticatedSelesaiRoute: authenticatedSelesaiRoute,
  authenticatedUbahPasswordRoute: authenticatedUbahPasswordRoute,
  authenticatedDetailIdRoute: authenticatedDetailIdRoute,
  authenticatedPenilaianIdpenilaianRoute:
    authenticatedPenilaianIdpenilaianRoute,
}

const authenticatedRouteWithChildren = authenticatedRoute._addFileChildren(
  authenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof authenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/akun': typeof authenticatedAkunRoute
  '/dashboard': typeof authenticatedDashboardRoute
  '/pekerjaan': typeof authenticatedPekerjaanRoute
  '/profile': typeof authenticatedProfileRoute
  '/qrscan': typeof authenticatedQrscanRoute
  '/selesai': typeof authenticatedSelesaiRoute
  '/ubah-password': typeof authenticatedUbahPasswordRoute
  '/detail/$id': typeof authenticatedDetailIdRoute
  '/penilaian/$id_penilaian': typeof authenticatedPenilaianIdpenilaianRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof authenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/akun': typeof authenticatedAkunRoute
  '/dashboard': typeof authenticatedDashboardRoute
  '/pekerjaan': typeof authenticatedPekerjaanRoute
  '/profile': typeof authenticatedProfileRoute
  '/qrscan': typeof authenticatedQrscanRoute
  '/selesai': typeof authenticatedSelesaiRoute
  '/ubah-password': typeof authenticatedUbahPasswordRoute
  '/detail/$id': typeof authenticatedDetailIdRoute
  '/penilaian/$id_penilaian': typeof authenticatedPenilaianIdpenilaianRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/__authenticated': typeof authenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/__authenticated/akun': typeof authenticatedAkunRoute
  '/__authenticated/dashboard': typeof authenticatedDashboardRoute
  '/__authenticated/pekerjaan': typeof authenticatedPekerjaanRoute
  '/__authenticated/profile': typeof authenticatedProfileRoute
  '/__authenticated/qrscan': typeof authenticatedQrscanRoute
  '/__authenticated/selesai': typeof authenticatedSelesaiRoute
  '/__authenticated/ubah-password': typeof authenticatedUbahPasswordRoute
  '/__authenticated/detail/$id': typeof authenticatedDetailIdRoute
  '/__authenticated/penilaian/$id_penilaian': typeof authenticatedPenilaianIdpenilaianRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/login'
    | '/akun'
    | '/dashboard'
    | '/pekerjaan'
    | '/profile'
    | '/qrscan'
    | '/selesai'
    | '/ubah-password'
    | '/detail/$id'
    | '/penilaian/$id_penilaian'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/login'
    | '/akun'
    | '/dashboard'
    | '/pekerjaan'
    | '/profile'
    | '/qrscan'
    | '/selesai'
    | '/ubah-password'
    | '/detail/$id'
    | '/penilaian/$id_penilaian'
  id:
    | '__root__'
    | '/'
    | '/__authenticated'
    | '/about'
    | '/login'
    | '/__authenticated/akun'
    | '/__authenticated/dashboard'
    | '/__authenticated/pekerjaan'
    | '/__authenticated/profile'
    | '/__authenticated/qrscan'
    | '/__authenticated/selesai'
    | '/__authenticated/ubah-password'
    | '/__authenticated/detail/$id'
    | '/__authenticated/penilaian/$id_penilaian'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRoute: typeof authenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRoute: authenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__authenticated",
        "/about",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/__authenticated": {
      "filePath": "__authenticated.tsx",
      "children": [
        "/__authenticated/akun",
        "/__authenticated/dashboard",
        "/__authenticated/pekerjaan",
        "/__authenticated/profile",
        "/__authenticated/qrscan",
        "/__authenticated/selesai",
        "/__authenticated/ubah-password",
        "/__authenticated/detail/$id",
        "/__authenticated/penilaian/$id_penilaian"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/__authenticated/akun": {
      "filePath": "__authenticated/akun.tsx",
      "parent": "/__authenticated"
    },
    "/__authenticated/dashboard": {
      "filePath": "__authenticated/dashboard.tsx",
      "parent": "/__authenticated"
    },
    "/__authenticated/pekerjaan": {
      "filePath": "__authenticated/pekerjaan.tsx",
      "parent": "/__authenticated"
    },
    "/__authenticated/profile": {
      "filePath": "__authenticated/profile.tsx",
      "parent": "/__authenticated"
    },
    "/__authenticated/qrscan": {
      "filePath": "__authenticated/qrscan.tsx",
      "parent": "/__authenticated"
    },
    "/__authenticated/selesai": {
      "filePath": "__authenticated/selesai.tsx",
      "parent": "/__authenticated"
    },
    "/__authenticated/ubah-password": {
      "filePath": "__authenticated/ubah-password.tsx",
      "parent": "/__authenticated"
    },
    "/__authenticated/detail/$id": {
      "filePath": "__authenticated/detail/$id.tsx",
      "parent": "/__authenticated"
    },
    "/__authenticated/penilaian/$id_penilaian": {
      "filePath": "__authenticated/penilaian/$id_penilaian.tsx",
      "parent": "/__authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
